language: python

python:
  - "3.6"

services:
  - postgresql

before_script:
  - psql -c 'create database test_requests;' -U postgres

install:
  - cp contrib/env-sample.txt .env
  - pip install --upgrade -r requirements/requirements.txt
  - pip install --upgrade -r requirements/test.txt
  - pip install coveralls --quiet

script: make test

after_success: coveralls