"""empty message

Revision ID: 33bee8923c5d
Revises: 742d67aa10b4
Create Date: 2017-09-22 17:00:57.539584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33bee8923c5d'
down_revision = '742d67aa10b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('priority', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('priority', sa.Column('id', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
