"""empty message

Revision ID: 638ef584f635
Revises: b2cc85d7668c
Create Date: 2017-09-21 18:37:46.001687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '638ef584f635'
down_revision = 'b2cc85d7668c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_request', sa.Column('product_area', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feature_request', 'product_area')
    # ### end Alembic commands ###
