"""empty message

Revision ID: f03f2b38516a
Revises: 33bee8923c5d
Create Date: 2017-09-22 17:35:03.727805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f03f2b38516a'
down_revision = '33bee8923c5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('priority')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('priority',
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
