"""empty message

Revision ID: b2cc85d7668c
Revises: e452cbdd492c
Create Date: 2017-09-21 17:06:14.672046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2cc85d7668c'
down_revision = 'e452cbdd492c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('priority')
    op.add_column('feature_request', sa.Column('priority', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feature_request', 'priority')
    op.create_table('priority',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='priority_pkey')
    )
    # ### end Alembic commands ###
